$(document).ready(function(){
	setTimeout(function(){
		$(".pic_2").css("display","block");
	},3000);
	setTimeout(function(){
		$(".pic_3").css("display","block");
	},6000);
	setTimeout(function(){
		$(".pic_4").css("display","block");
	},9000);
	setTimeout(function(){
		$(".pic_5").css("display","block");
	},12000);
	setTimeout(function(){
		$(".images").fadeOut();
	},21*1000);
	setTimeout(function(){
		$(".progress-bg").fadeOut();
	},30*1000);
});
